development:
  adapter: postgresql
  encoding: utf8
  database: portfolio
  username: montt
  password:
  host: localhost

test:
  adapter: postgresql
  encoding: utf8
  database: portfolio_test
  username: montt
  password:
  host: localhost
